server:
  port: 9001
spring:
  application:
    name: shicifang-base #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.122.128:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true